/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ieee_hardlibrary_HardControl */

#ifndef _Included_ieee_hardlibrary_HardControl
#define _Included_ieee_hardlibrary_HardControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ieee_hardlibrary_HardControl
 * Method:    ledCtrl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ieee_hardlibrary_HardControl_ledCtrl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ieee_hardlibrary_HardControl
 * Method:    ledOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieee_hardlibrary_HardControl_ledOpen
  (JNIEnv *, jclass);

/*
 * Class:     ieee_hardlibrary_HardControl
 * Method:    ledClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ieee_hardlibrary_HardControl_ledClose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
